#!/bin/sh

docker run \
         -it \
         --rm \
         --network overviewserver_default \
         -e 'POLL_URL=http://overview-web:9032/Archive' \
         $(docker build --target=test -q .) \
         "$@"
